# fly.toml app configuration file generated for dms-api on 2023-07-08T13:43:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dms-api"
primary_region = "jnb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  strategy = "bluegreen"
