name: Deploy UI to Fly
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backend/**'
jobs:
  deploy:
    name: Deploy UI to Fly
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy React app to fly.io
        run: cd frontend && fly deploy --remote-only